# Generated by Django 2.0 on 2021-06-27 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id_depa', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_depa', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'departamento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id_muni', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_muni', models.CharField(max_length=50)),
                ('id_depart', models.IntegerField()),
            ],
            options={
                'db_table': 'municipio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Entrevista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_usuario', models.CharField(max_length=5, verbose_name='Nombre entrevistador')),
                ('id_depa', models.CharField(max_length=2, verbose_name='Departamento')),
                ('id_muni', models.CharField(max_length=3, verbose_name='Municipio')),
                ('id_vacuna', models.CharField(max_length=30, verbose_name='Dosis')),
            ],
            options={
                'verbose_name': 'Entrevista',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('contraseña', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Usuario',
            },
        ),
        migrations.CreateModel(
            name='Vacuna',
            fields=[
                ('id_vacuna', models.IntegerField(primary_key=True, serialize=False)),
                ('dosis1', models.BooleanField(default=False)),
                ('dosis2', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Vacuna',
            },
        ),
    ]
