# Generated by Django 2.0 on 2021-06-18 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id_depa', models.IntegerField(max_length=2, primary_key=True, serialize=False)),
                ('nombre_depa', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Encuesta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_encuestador', models.CharField(max_length=5)),
                ('id_depa', models.CharField(max_length=2)),
                ('id_muni', models.CharField(max_length=3)),
                ('id_vacuna', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Encuestador',
            fields=[
                ('id_encuestador', models.CharField(max_length=5, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id_muni', models.IntegerField(max_length=3, primary_key=True, serialize=False)),
                ('nombre_muni', models.CharField(max_length=50)),
                ('departamento', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='fennechpage.Departamento')),
            ],
        ),
        migrations.CreateModel(
            name='Vacuna',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_vacuna', models.IntegerField(max_length=3)),
                ('dosis_1', models.BooleanField(default=False)),
                ('dosis_2', models.BooleanField(default=False)),
            ],
        ),
    ]
