# Generated by Django 2.0 on 2021-06-27 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fennechpage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrevista',
            name='id_depa',
            field=models.CharField(max_length=15, verbose_name='Departamento'),
        ),
        migrations.AlterField(
            model_name='entrevista',
            name='id_muni',
            field=models.CharField(max_length=50, verbose_name='Municipio'),
        ),
        migrations.AlterField(
            model_name='entrevista',
            name='id_vacuna',
            field=models.BooleanField(verbose_name='Dosis 2'),
        ),
    ]
