# Generated by Django 2.0 on 2021-06-19 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fennechpage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entrevista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_entrevistador', models.CharField(max_length=3, verbose_name='ID entrevistador')),
                ('id_depa', models.CharField(max_length=2, verbose_name='Departamento')),
                ('id_muni', models.CharField(max_length=3, verbose_name='Municipio')),
                ('id_vacuna', models.CharField(max_length=30, verbose_name='Dosis')),
            ],
            options={
                'verbose_name': 'Entrevista',
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_entrevistador', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Encuesta',
        ),
        migrations.DeleteModel(
            name='Encuestador',
        ),
        migrations.AlterModelOptions(
            name='departamento',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='municipio',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='vacuna',
            options={'verbose_name': 'Vacuna'},
        ),
        migrations.RenameField(
            model_name='vacuna',
            old_name='dosis_1',
            new_name='dosis1',
        ),
        migrations.RenameField(
            model_name='vacuna',
            old_name='dosis_2',
            new_name='dosis2',
        ),
        migrations.RemoveField(
            model_name='vacuna',
            name='id',
        ),
        migrations.AlterField(
            model_name='vacuna',
            name='id_vacuna',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
