# Generated by Django 2.0 on 2021-06-27 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fennechpage', '0002_auto_20210626_2117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacuna',
            name='dosis1',
        ),
        migrations.RemoveField(
            model_name='vacuna',
            name='dosis2',
        ),
        migrations.AddField(
            model_name='vacuna',
            name='dosis',
            field=models.BooleanField(default=False),
        ),
    ]
