# Generated by Django 2.0 on 2021-06-24 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fennechpage', '0002_auto_20210619_0144'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='departamento',
            table='departamento',
        ),
        migrations.AlterModelTable(
            name='municipio',
            table='municipio',
        ),
    ]
