# Generated by Django 2.0 on 2021-06-27 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fennechpage', '0003_auto_20210626_2342'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vacuna',
            old_name='dosis',
            new_name='dosis1',
        ),
        migrations.AddField(
            model_name='vacuna',
            name='dosis2',
            field=models.BooleanField(default=False),
        ),
    ]
